apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: function-avd
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
          - name: package-runtime
            resources:
              requests:
                cpu: "1"
                memory: 1Gi
              limits:
                cpu: "4"
                memory: 1Gi
---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: netclab-function-avd
spec:
  package: xpkg.upbound.io/netclab/function-avd:v0.2.0
  runtimeConfigRef:
    name: function-avd
