apiVersion: avd.netclab.dev/v1alpha1
kind: ConnectedEndpointSet
metadata:
  name: connected-endpoints
spec:
  design:
    servers:
    - adapters:
      - endpoint_ports:
        - PCI1
        - PCI2
        mode: trunk
        native_vlan: 4092
        port_channel:
          endpoint_port_channel: Bond1
          mode: active
        spanning_tree_portfast: edge
        switch_ports:
        - Ethernet5
        - Ethernet5
        switches:
        - dc1-leaf1a
        - dc1-leaf1b
        vlans: 11-12,21-22
      - endpoint_ports:
        - iLO
        mode: access
        spanning_tree_portfast: edge
        switch_ports:
        - Ethernet5
        switches:
        - dc1-leaf1c
        vlans: 11
      name: dc1-leaf1-server1
    - adapters:
      - endpoint_ports:
        - PCI1
        - PCI2
        mode: trunk
        native_vlan: 4092
        port_channel:
          mode: active
        spanning_tree_portfast: edge
        switch_ports:
        - Ethernet5
        - Ethernet5
        switches:
        - dc1-leaf2a
        - dc1-leaf2b
        vlans: 11-12,21-22
      - endpoint_ports:
        - iLO
        mode: access
        spanning_tree_portfast: edge
        switch_ports:
        - Ethernet5
        switches:
        - dc1-leaf2c
        vlans: 11
      name: dc1-leaf2-server1
  appliesTo:
    nodeSets:
    - dc1-l2-leaves
    - dc1-l3-leaves
---
apiVersion: avd.netclab.dev/v1alpha1
kind: SettingSet
metadata:
  name: fabric
spec:
  design:
    aaa_settings:
      local_users:
      - name: admin
        no_password: true
        privilege: 15
        role: network-admin
      - name: arista
        privilege: 15
        role: network-admin
        sha512_password: $6$Enl0WfE32FthwyiJ$yTyGaEJ2uPKLU.F7314YtB7J1jrzrMi7ogXIRTEHQfLdLgKWWmr1UvNlZLN6AyuxET7G5aH3AI9OYRzxVTkB1.
    bgp_peer_groups:
      evpn_overlay_peers:
        password: Q4fqtbqcZ7oQuKfuWtNGRQ==
      ipv4_underlay_peers:
        name: IPv6-UNDERLAY-PEERS
        password: F0bdF6JLcJtagc6PCN8W0Q==
      mlag_ipv4_underlay_peer:
        name: MLAG-IPv6-UNDERLAY-PEER
        password: GNtuK+/vTwZwSZiwj1FK/Q==
    cv_settings:
      onprem_clusters:
      - name: primary
        servers:
        - name: 192.168.1.12
      terminattr:
        disable_aaa: true
    default_interfaces:
    - downlink_interfaces:
      - Ethernet1-8
      platforms:
      - default
      types:
      - spine
      uplink_interfaces:
      - Ethernet1-2
    - downlink_interfaces:
      - Ethernet8
      mlag_interfaces:
      - Ethernet3-4
      platforms:
      - default
      types:
      - l3leaf
      uplink_interfaces:
      - Ethernet1-2
    - platforms:
      - default
      types:
      - l2leaf
      uplink_interfaces:
      - Ethernet1-2
    dns_settings:
      servers:
      - ip_address: 192.168.1.1
    eos_designs_documentation:
      p2p_links_csv: true
      topology_csv: true
    fabric_ip_addressing:
      loopback:
        ipv6_prefix_length: 64
      mlag:
        ipv6_prefix_length: 64
      p2p_uplinks:
        ipv6_prefix_length: 64
    fabric_name: FABRIC
    ntp_settings:
      server_vrf: use_mgmt_interface_vrf
      servers:
      - name: 0.pool.ntp.org
    overlay_routing_protocol: ebgp
    underlay_ipv6: true
    underlay_ipv6_numbered: true
    underlay_routing_protocol: ebgp
  appliesTo:
    all: true
---
apiVersion: avd.netclab.dev/v1alpha1
kind: NetworkServiceSet
metadata:
  name: network-services
spec:
  design:
    tenants:
    - l2vlans:
      - id: 3401
        name: L2_VLAN3401
      - id: 3402
        name: L2_VLAN3402
      mac_vrf_vni_base: 10000
      name: TENANT1
      vrfs:
      - name: VRF10
        svis:
        - enabled: true
          id: 11
          ip_address_virtual: 10.10.11.1/24
          name: VRF10_VLAN11
        - enabled: true
          id: 12
          ip_address_virtual: 10.10.12.1/24
          name: VRF10_VLAN12
        vrf_vni: 10
        vtep_diagnostic:
          loopback: 10
          loopback_ip_range: 10.255.10.0/27
      - name: VRF11
        svis:
        - enabled: true
          id: 21
          ipv6_address_virtuals:
          - 2001:DB8:21::1/48
          name: VRF11_VLAN21
        - enabled: true
          id: 22
          ip_address_virtual: 10.10.22.1/24
          name: VRF11_VLAN22
        vrf_vni: 11
        vtep_diagnostic:
          loopback: 11
          loopback_ip_range: 10.255.11.0/27
      - name: VRF12
        svis:
        - enabled: true
          id: 31
          ipv6_address_virtuals:
          - 2001:DB8:31::1/48
          name: VRF12_VLAN31
        - enabled: true
          id: 32
          ipv6_address_virtuals:
          - 2001:DB8:32::1/48
          name: VRF12_VLAN32
        vrf_vni: 12
        vtep_diagnostic:
          loopback: 12
          loopback_ip_range: 10.255.12.0/27
  appliesTo:
    nodeSets:
    - dc1-l2-leaves
    - dc1-l3-leaves
---
apiVersion: avd.netclab.dev/v1alpha1
kind: SettingSet
metadata:
  name: dc1
spec:
  design:
    management_eapi:
      enabled: true
    mgmt_gateway: 172.16.1.1
  appliesTo:
    all: true
---
apiVersion: avd.netclab.dev/v1alpha1
kind: NodeSet
metadata:
  name: dc1-l2-leaves
spec:
  design:
    l2leaf:
      defaults:
        platform: cEOSLab
        spanning_tree_mode: mstp
      node_groups:
      - group: DC1_L2_LEAF1
        nodes:
        - id: 1
          mgmt_ip: 172.16.1.151/24
          name: dc1-leaf1c
        uplink_switches:
        - dc1-leaf1a
        - dc1-leaf1b
      - group: DC1_L2_LEAF2
        nodes:
        - id: 1
          mgmt_ip: 172.16.1.152/24
          name: dc1-leaf2c
        uplink_switches:
        - dc1-leaf2a
        - dc1-leaf2b
    type: l2leaf
  declares:
  - dc1-leaf1c
  - dc1-leaf2c
---
apiVersion: avd.netclab.dev/v1alpha1
kind: NodeSet
metadata:
  name: dc1-l3-leaves
spec:
  design:
    l3leaf:
      defaults:
        loopback_ipv6_pool: 2001:DB8:1::/48
        mlag_peer_address_family: ipv6
        mlag_peer_ipv6_pool: 2001:DB8:3::/48
        mlag_peer_l3_ipv6_pool: 2001:DB8:4::/48
        platform: cEOSLab
        router_id_pool: 10.255.1.0/24
        spanning_tree_mode: mstp
        spanning_tree_priority: 4096
        uplink_ipv6_pool: 2001:DB8:2::/48
        uplink_switches:
        - dc1-spine1
        - dc1-spine2
        virtual_router_mac_address: 00:1c:73:00:00:99
        vtep_loopback_ipv6_pool: 2001:DB8:5::/48
      node_groups:
      - bgp_as: 65101
        group: DC1_L3_LEAF1
        nodes:
        - id: 1
          mgmt_ip: 172.16.1.101/24
          name: dc1-leaf1a
        - id: 2
          mgmt_ip: 172.16.1.102/24
          name: dc1-leaf1b
      - bgp_as: 65102
        group: DC1_L3_LEAF2
        nodes:
        - id: 3
          mgmt_ip: 172.16.1.103/24
          name: dc1-leaf2a
        - id: 4
          mgmt_ip: 172.16.1.104/24
          name: dc1-leaf2b
    type: l3leaf
  declares:
  - dc1-leaf1a
  - dc1-leaf1b
  - dc1-leaf2a
  - dc1-leaf2b
---
apiVersion: avd.netclab.dev/v1alpha1
kind: NodeSet
metadata:
  name: dc1-spines
spec:
  design:
    spine:
      defaults:
        bgp_as: 65100
        loopback_ipv6_pool: 2001:DB8:0::/48
        platform: cEOSLab
        router_id_pool: 10.255.0.0/24
      nodes:
      - id: 1
        mgmt_ip: 172.16.1.11/24
        name: dc1-spine1
      - id: 2
        mgmt_ip: 172.16.1.12/24
        name: dc1-spine2
    type: spine
  declares:
  - dc1-spine1
  - dc1-spine2
---
apiVersion: avd.netclab.dev/v1alpha1
kind: Fabric
metadata:
  name: single-dc-l3ls-ipv6
spec:
  fabricName: FABRIC
  requires:
  - kind: ConnectedEndpointSet
    name: connected-endpoints
  - kind: SettingSet
    name: fabric
  - kind: NetworkServiceSet
    name: network-services
  - kind: SettingSet
    name: dc1
  - kind: NodeSet
    name: dc1-l2-leaves
  - kind: NodeSet
    name: dc1-l3-leaves
  - kind: NodeSet
    name: dc1-spines
