apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: device-avd
spec:
  compositeTypeRef:
    apiVersion: avd.netclab.dev/v1alpha1
    kind: Device
  mode: Pipeline
  pipeline:
    - step: render
      functionRef:
        name: netclab-function-avd
